$ProjectPath = "C:\Users\HP\Desktop\FlowPilot-Final-Merged"

Write-Host "Checking: $ProjectPath"
Write-Host "docker-compose.yml: $(Test-Path (Join-Path $ProjectPath 'docker-compose.yml'))"
Write-Host "web/package.json: $(Test-Path (Join-Path $ProjectPath 'web\package.json'))"
Write-Host "web/prisma/schema.prisma: $(Test-Path (Join-Path $ProjectPath 'web\prisma\schema.prisma'))"
Write-Host "web/next.config.js: $(Test-Path (Join-Path $ProjectPath 'web\next.config.js'))"
Write-Host "web/Dockerfile: $(Test-Path (Join-Path $ProjectPath 'web\Dockerfile'))"
Write-Host "web/tsconfig.json: $(Test-Path (Join-Path $ProjectPath 'web\tsconfig.json'))"
Write-Host "web/middleware.ts: $(Test-Path (Join-Path $ProjectPath 'web\middleware.ts'))"
Write-Host ".env.example: $(Test-Path (Join-Path $ProjectPath '.env.example'))"
Write-Host "README.md: $(Test-Path (Join-Path $ProjectPath 'README.md'))"
Write-Host "scripts/setup-env.sh: $(Test-Path (Join-Path $ProjectPath 'scripts\setup-env.sh'))"
Write-Host "coolify/README.md: $(Test-Path (Join-Path $ProjectPath 'coolify\README.md'))"